rm gameResults.txt
touch gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
python createGameSample.py officialSampleClean.txt >>gameResults.txt
